name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.ref_name }}-${{
    github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: "build image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: test_opik:latest
          cache-from: type=gha,scope=test_opik
          cache-to: type=gha,mode=min,scope=test_opik
          outputs: type=docker,dest=/tmp/test_opik.tar

      - name: Build and export (multistage)
        uses: docker/build-push-action@v6
        with:
          file: multistage.Dockerfile
          tags: test_opik-multistage:latest
          cache-from: type=gha,scope=test_opik-multistage
          cache-to: type=gha,mode=min,scope=test_opik-multistage
          outputs: type=docker,dest=/tmp/test_opik-multistage.tar

      - name: Build and export (standalone)
        uses: docker/build-push-action@v6
        with:
          file: standalone.Dockerfile
          tags: test_opik-standalone:latest
          cache-from: type=gha,scope=test_opik-standalone
          cache-to: type=gha,mode=min,scope=test_opik-standalone
          outputs: type=docker,dest=/tmp/test_opik-standalone.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_opik
          path: /tmp/test_opik.tar

      - name: Upload artifact (multistage)
        uses: actions/upload-artifact@v4
        with:
          name: test_opik-multistage
          path: /tmp/test_opik-multistage.tar

      - name: Upload artifact (standalone)
        uses: actions/upload-artifact@v4
        with:
          name: test_opik-standalone
          path: /tmp/test_opik-standalone.tar

  test:
    name: "test image"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test_opik
          path: /tmp

      - name: Download artifact (multistage)
        uses: actions/download-artifact@v4
        with:
          name: test_opik-multistage
          path: /tmp

      - name: Download artifact (standalone)
        uses: actions/download-artifact@v4
        with:
          name: test_opik-standalone
          path: /tmp
  
      - name: Load images
        run: |
          docker load --input /tmp/test_opik.tar
          docker load --input /tmp/test_opik-multistage.tar
          docker load --input /tmp/test_opik-standalone.tar
          docker image ls -a

      - name: Test command line
        run: ./run.sh hello

      - name: Test Docker compose
        run: |
          docker compose up -d
          docker compose down

      - name: Test command line (multistage)
        run: docker run test_opik-multistage:latest hello

      - name: Test command line (standalone)
        run: docker run test_opik-standalone:latest hello
